## TYPES OF INHERITANCE IN PYTHON

## 1 Single Inheritance.

In [2]:
class parent:
    def function1(self):
        print("The funciton is in Parent class.")
class children(parent):
    def function2(self):
        print("The function is in Child class.")
obj = children()
obj.function1()
obj.function2()

The funciton is in Parent class.
The function is in Child class.


## 2 Multiple Inheritance.

In [ ]:
class Mother:
    mothername = ""
 
    def mother(self):
        print(self.mothername)
 
 
class Father:
    fathername = ""
 
    def father(self):
        print(self.fathername)
 
 
class Son(Mother, Father):
    def parents(self):
        print("Father's Name:", self.fathername)
        print("Mother's Name:", self.mothername)
 
 
s1 = Son()
s1.fathername = "Kum"
s1.mothername = ""
s1.parents()

## 3 Multi-Level Inheritance.

In [ ]:
class Grandfather:
 
    def __init__(self, grandfathername):
        self.grandfathername = grandfathername
 
 
class Father(Grandfather):
    def __init__(self, fathername, grandfathername):
        self.fathername = fathername

        Grandfather.__init__(self, grandfathername)
 
class Son(Father):
    def __init__(self, sonname, fathername, grandfathername):
        self.sonname = sonname
 
        
        Father.__init__(self, fathername, grandfathername)
 
    def print_name(self):
        print("Grandfather's name :", self.grandfathername)
        print("Father's name :", self.fathername)
        print("Son's name :", self.sonname)
 
 

s1 = Son()
print(s1.grandfathername)
s1.print_name()

## 4 Hierarchical Inheritance.

In [3]:
class Parent:
    def func1(self):
        print("The function is in Parent class.")
 
 
class Child1(Parent):
    def func2(self):
        print("The function is in Second Child.")
 
 
class Child2(Parent):
    def func3(self):
        print("The function is in First Child.")
 
object1 = Child1()
object2 = Child2()
object1.func1()
object1.func2()
object2.func1()
object2.func3()

The function is in Parent class.
The function is in Second Child.
The function is in Parent class.
The function is in First Child.


## 5 Hybrid Inheritance.

In [4]:
class School:
    def func1(self):
        print("The function is in College.")
 
 
class Student1(School):
    def func2(self):
        print("The function is in Student 1. ")
 
 
class Student2(School):
    def func3(self):
        print("The function is in Student 2.")
 
 
class Student3(Student1, School):
    def func4(self):
        print("The function is in Student 3.")
 
object = Student3()
object.func1()
object.func2()

The function is in College.
The function is in Student 1. 


# EXCEPTION HANDLING IN PYTHON.

## 1 ZeroDivisionError.

In [5]:
marks = 10000
try:
    a = marks / 0 
    print(a)
except:
    print ("An error occurred !!")
    print(marks)

An error occurred !!
10000


## 2 Unexpected Indent.

In [7]:
a = [1, 2, 3]
try: 
    print ("First element = %d" %(a[1]))
  
    # Throws error since there are only 3 elements in array
    print ("Fourth element = %d" %(a[3]))
  
except:
    print ("An error occurred !!")

First element = 2
An error occurred !!


## 3 Value Error.

In [8]:
while True:
    try:
        x = int(input("Please enter a number: "))
        break
    except ValueError:
            print("Invalid Number! Please Enter a Number")

Please enter a number: skjf
Invalid Number! Please Enter a Number
Please enter a number: 2


## 4 File Opening Error.

In [9]:
try:
    f = open("demofile.txt")
    try:
        f.write("Lorum Ipsum")
    except:
        print("Something Went Wrong! Try Again.")
    finally:
        f.close()
except:           
        print("Something Went Wrong! Try Again.")

Something Went Wrong! Try Again.


## 5 Indentation Error.

In [10]:
a = 10
try:
     b = 19
     c = a+b
except:
    print("Indentation Error!")
print(c)

29


## 6 Name Error.

In [11]:
try:
    print(s)
except NameError:
    print("Variable s is undefined")
except:
    print("Something else went wrong")

Variable s is undefined


# REGULAR EXPRESSION IN PYTHON.

## Findall()

In [13]:
import re

word = "Save Water Save Future"
x = re.findall("av", word)
print(x)

['av', 'av']


## Search()

In [14]:
import re

par = "Hello Everyone"
x = re.search("\s", par)

print("The located in position:", x.start())

The located in position: 5


## Split()

In [15]:
import re
sen = "Thank You Everyone"
x = re.split("\s", sen)
print(x)

['Thank', 'You', 'Everyone']


## Sub()

In [17]:
import re
part = "Ha B.tech AI&DS"
x = re.sub("\s", "-", part)
print(x)

Ha-B.tech-AI&DS


# AGGREGATE FUNCTIONS IN PYTHON.

In [18]:
import numpy as np
arr1 = np.array([10,22,37,80,51])
arr1
b = np.array([20,14,45,56,78])
print(b)

[20 14 45 56 78]


In [19]:
arr2 = np.array([[10,20,30],[20,40,50],[30,40,50]])
arr2

array([[10, 20, 30],
       [20, 40, 50],
       [30, 40, 50]])

## Sum Function.

In [20]:
ar=np.array([42,53,5,6,35,3,2,5,4,54,43,4,6])
ar.sum()

262

In [21]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2.sum(axis = 0)

array([12, 15, 18])

In [ ]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2.sum(axis = 1)

## Porduct Function.

In [22]:
arr1 = np.array([1,2,3,4,5])
np.prod(arr1)

120

In [23]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.product(arr2,axis = 0)

array([ 28,  80, 162])

In [24]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.prod(arr2,axis = 1)

array([  6, 120, 504])

## Average Function.

In [25]:
arr1 = np.array([1,2,3,4,5])
np.average(arr1)

3.0

In [26]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.average(arr2,axis =0)

array([4., 5., 6.])

## Minimum Function.

In [27]:
arr1 = np.array([1,2,3,4,5])
arr1.min()

1

In [28]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2.min(axis = 0)

array([1, 2, 3])

In [29]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2.min(axis = 1)

array([1, 4, 7])

In [30]:
import numpy as np
x = np.random.randint(1, 10, size = (4,4))
print(x)
print()
 
y = np.random.randint(1, 10, size = (4,4))
print(y)
 
print('\nMinimum Array')
print(np.minimum(x, y))

[[5 1 2 7]
 [2 3 9 6]
 [9 4 1 1]
 [6 9 8 9]]

[[7 2 2 7]
 [4 4 8 7]
 [8 5 8 4]
 [1 2 7 1]]

Minimum Array
[[5 1 2 7]
 [2 3 8 6]
 [8 4 1 1]
 [1 2 7 1]]


In [31]:
import numpy as np
x = np.random.randint(1, 10, size = (4,4))
print(x)
print()
 
y = np.random.randint(1, 10, size = (4,4))
print(y)
 
print('\nMaximum Matrix:')
print(np.maximum(x, y))

[[8 5 1 2]
 [5 7 4 8]
 [3 5 4 9]
 [6 1 1 5]]

[[1 4 4 3]
 [5 8 2 2]
 [1 7 1 2]
 [1 9 5 7]]

Maximum Matrix:
[[8 5 4 3]
 [5 8 4 8]
 [3 7 4 9]
 [6 9 5 7]]


## Mean Function.

In [32]:
arr1 = np.array([1,2,3,4,5])
np.mean(arr1)

3.0

In [33]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.mean(arr2)

5.0

## Median Function.

In [34]:
arr1 = np.array([1,2,3,4,5])
np.median(arr1)

3.0

In [35]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.median(arr2)

5.0

In [36]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.median(arr2, axis = 0)

array([4., 5., 6.])

In [37]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.median(arr2, axis = 1)

array([2., 5., 8.])